version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  website:
    stdin_open: true
    tty: true
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/app'
    volumes_from:
      - box
  box:
    image: busybox
    volumes:
      - /box
volumes:
  postgres:
  box:
